version: "3.7"
services:
  api:
    stdin_open: true
    image: api-be
    tty: true
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
    command: python manage.py
    env_file:
      - src/.env
    depends_on:
      - db
  db:
    image: postgres:12.9-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./db.env

volumes:
  db-data: null
